name: Windows unit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Windows unit
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: make build directory
        run: mkdir build_dir

      - name: cmake configure
        run: cmake -S . -B build_dir -DCMAKE_BUILD_TYPE=Debug -Dtrase_BUILD_OPENGL:BOOL=FALSE

      - name: cmake build
        run: cmake --build build_dir --parallel 2

      - name: cmake test
        run: ctest -j2 --output-on-failure
        working-directory: build_dir
